### PR TITLE
latest French translation

### PR DESCRIPTION
**Pull request by mhvezina**
mainly text related to the new Portage site/branding

### CODE REVIEW

**Comment by mhvezina** [comment]
Weiwei, we still have more text to translate (about page + help page). We will try to do so before the week-end.

**Comment by weiweishi** [comment]
Thanks @mhvezina. At least now all the text required by the function of the tool is in place.

**Comment by mhvezina** [comment]
Just did a pull request (https://github.com/ualbertalib/DMPonline_v4/pull/64) with the latest translation.

**Comment by weiweishi** [comment]
Was there any more translation that you'd like to put in? thank you so very
much Marie-Helene!

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by mhvezina** [comment]
Thanks to YOU! You did a terrific job.

Yes, I just realized that I didn't review/translate
  terms_page >   body_text_html within fr.yml.
I will do so and let you know. Also I will log a few issues (maybe later today if I can) related to translated text within the database (template). Maybe some of the "step" images too needs to be translated...will see...

**Comment by mhvezina** [comment]
Yep images here : app/assets/images/step_*.jpg needs to be translated: "Étape 1", "Étape 2",.....

**Pull request merged**
